[SERVER]
port = 8893
certfile = certs/radio.vlsc.net.pem
keyfile = certs/radio.vlsc.net.key
auth = FILE
cookie_secret = L8LwECiNRxq2N0N2eGxx9MZlrpmuMEimlydNX/vt1LM=
db_users_file = MRRC_users.db
pam_account = pi
log_file = MRRC.log
debug = False

[CTRL]
interval_smeter_update = 5.0
debug = False

[AUDIO]
outputdevice = USB Audio CODEC
inputdevice = USB Audio CODEC

[HAMLIB]
rig_pathname = /dev/cu.usbserial-230
retry = 5
rig_model = IC_M710
trxautopower = True
rig_rate = 4800
data_bits = 
stop_bits = 2
serial_parity = 
serial_handshake = 
dtr_state = 
rts_state = 

[RNNOISE]
enabled = False
suppress_level = 50

[WDSP]
enabled = True
sample_rate = 48000
buffer_size = 256
agc_mode = 2
nr2_enabled = True
nr2_level = 1
nr2_gain_method = 2
nr2_npe_method = 1
nr2_ae_run = True
nr_enabled = False
nr_level = 2
nb_enabled = True
nb2_enabled = False
anf_enabled = True
bandpass_low = 300.0
bandpass_high = 2700.0
tx_eq_enabled = False
tx_eq_low = 4.0
tx_eq_mid = 6.0
tx_eq_high = -3.0

[PANADAPTER]
sample_rate = 960000
center_freq = 68330000
freq_correction = 1
gain = 10
fft_window = hamming

[INSTANCE_SETTINGS]
instance_name = radio3
instance_port = 8893
instance_rigctl_device = /dev/cu.usbserial-NEW
instance_rigctl_model = 30003
instance_rigctl_speed = 4800
instance_rigctl_stop_bits = 2
instance_rigctl_host = 127.0.0.1
instance_rigctl_port = 4533
instance_audio_input = USB Audio CODEC
instance_audio_output = USB Audio CODEC
instance_atr1000_device = 
instance_atr1000_port = 60001
instance_log_dir = /Users/cheenle/UHRR/MRRC
instance_unix_socket = /tmp/mrrc_radio3.sock

